# docker-compose.yml

version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.s
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
  client:
    build:
      context: .
      dockerfile: Dockerfile.c
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development

